### ISSUE TITLE
Invalid plugin.yml

### ISSUE THREAD

**Issue by Titely** [DynamicThijs/KeepChunks#4]
Hello, I've had this exception after I updated to version 1.3.3:
```
[Server thread/ERROR]: Could not load 'plugins/KeepChunks.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:160) ~[spigot.jar:git-Spigot-a3f6ea5-a2af8f0]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [spigot.jar:git-Spigot-a3f6ea5-a2af8f0]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.loadPlugins(CraftServer.java:301) [spigot.jar:git-Spigot-a3f6ea5-a2af8f0]
        at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:204) [spigot.jar:git-Spigot-a3f6ea5-a2af8f0]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot.jar:git-Spigot-a3f6ea5-a2af8f0]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.util.zip.ZipException: zip file is empty
        at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_121]
        at java.util.zip.ZipFile.<init>(ZipFile.java:219) ~[?:1.8.0_121]
        at java.util.zip.ZipFile.<init>(ZipFile.java:149) ~[?:1.8.0_121]
        at java.util.jar.JarFile.<init>(JarFile.java:166) ~[?:1.8.0_121]
        at java.util.jar.JarFile.<init>(JarFile.java:130) ~[?:1.8.0_121]
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:148) ~[spigot.jar:git-Spigot-a3f6ea5-a2af8f0]
```

**Comment by DynamicThijs** [comment]
Hi there, can you stop your server, delete the KeepChunks.jar and download a fresh copy from [here](https://www.spigotmc.org/resources/keepchunks.23307/)?

**Comment by Titely** [comment]
I tried but I still have the same problem :/

**Comment by DynamicThijs** [comment]
Can you send me the jar that's currently in your server?

**Comment by Titely** [comment]
[KeepChunks.zip](https://github.com/DynamicThijs/KeepChunks/files/964222/KeepChunks.zip)

**Comment by DynamicThijs** [comment]
That's a .zip file, have you dropped that in your server?

**Comment by Titely** [comment]
No it's just that github didn't let me push the jar file

**Comment by DynamicThijs** [comment]
The jar works for me, have you edited a file within the jar?

**Comment by Titely** [comment]
No I didn't :/ Maybe it's because I recently updated spigot ?

**Comment by DynamicThijs** [comment]
That might be possible, can you send me the output of /version?

**Comment by Titely** [comment]
![dsfsdf](https://cloud.githubusercontent.com/assets/9611606/25527484/398ecae4-2c19-11e7-88d5-2e9a18b0e490.PNG)

**Comment by DynamicThijs** [comment]
Really weird, no one has this issue. I will try it soon with the latest Spigot build

**Comment by DynamicThijs** [comment]
Sorry for the delay, but for me it works with the very latest build

**Comment by Titely** [comment]
Ok that's weird, I will try to find a solution. Thanks for your help

**Comment by DynamicThijs** [comment]
Yea I'm sorry that I can't help you any further, but your jar is correct, so it must be a problem on your side.

**Comment by DynamicThijs** [comment]
Try KC v1.3.4, that MIGHT fix it, although I'm not sure because it's a really weird issue.

**Comment by Titely** [comment]
Well, it works so thank you

**Comment by DynamicThijs** [comment]
Does it? Great!
